1-conveyor_first_step
rk9-denford/fms_hardware pull request #3
Opened 2018-06-16 11:00 UTC by dmitriev-z

2018-06-17 18:22 UTC, yoshi-lyosha commented
Остальное, вроде, ок. Повторное ревью необходимо после всех фиксов, так как они весьма глобальными будут.

2018-06-17 18:23 UTC, yoshi-lyosha commented
Необходим файл с хоть каким-то намёком на тестовый сценарий. Мне не оч нравится что ты дебажишь прям на железе то, что мог бы подебажить и дома. Если нужна помощь с патчем/моком - напиши, я без проблем тебе это сделаю.

2018-06-18 08:55 UTC, yoshi-lyosha requested changes
Остальное, вроде, ок. Повторное ревью необходимо после всех фиксов, так как они весьма глобальными будут.

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +class ConveyorError(Exception):
Не понял что это, зачем, и какой юзкейс

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        GPIO.output(7, GPIO.HIGH)
А вот это вообще интересно. В методе, задача которого вывести строковое представление объекта - делать что-то связанное с GPIO. Зачем так?

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        sleep(0.8)
Предлагаю вынести 0.8 как переменную класса

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +            return 'YES'
Переделать на более очевидный True/False

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        return self._name.upper()
Предлагаю наоборот, либо хранить в нижнем регистре и преобразовывать всегда в нижний при поиске по имени, либо не трогать регистр вообще.

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        self._state = 'closed'
state переделать под [enum.Enum](https://docs.python.org/3/library/enum.html#creating-an-enum)

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        return {lock.name: {'is_busy': lock.is_busy, 'state': lock.state}}
Но после переделки под Enum возвращать объект Enum не парясь. Уже всё то, что будет работать с этим модулем будет использовать это так, как заблагорассудится. Если говорить про веб апи - то, например, возращать прям "status": {"name": Enum.name, "value": Enum.value}

Это не сложно и крайне приятно, попробуй

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        return {lock.name: {'is_busy': lock.is_busy, 'state': lock.state} for lock in self.locks}
Переделать. Ты принимаешь везде lock_id, а отдаёшь lock.name.

Пускай метод locks_state возвращает список словарей:
```
[
  {"name": lock.name,
   "id": lock.id,
   "state": lock.state,
   "is_busy": lock.is_busy},
  ...
}

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        return {lock.name: {'is_busy': lock.is_busy, 'state': lock.state} for lock in self.locks}
Соответственно - тебе нужно придумать как ты будешь задавать этим самым замкам этот самый id. Самое простое - добавить в класс замка поле id наряду с name.


А методы класса конвейер, связанные с замками - переделать. Они будут ожидать на вход в себя либо строку-имя, либо инт-айди.

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        return {lock.name: {'is_busy': lock.is_busy, 'state': lock.state} for lock in self.locks}
Другой вариант - при инициализации класса Conveyor добавить цикл, который пробежится по списку переданных ему замков с фукнцией enumerate и проставить им всем порядковый id просто. Тоже варич, работать будет, и не придётся задумываться про валидацию типа "а не ебанёт ли мне пользователь два замка с одинаковым именем и id". 


Наверное, это - самый простой и верный вариант.

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        return repr(self.msg)
Почему, кстати, в __str__ методе ты возвращаешь __repr__ потенциальной стринги в переменной `msg`?

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +class Conveyor:
Добавь, пожалуйста, в конце файла `if __name__ == "__main__":` и засунь туда инициализацию твоего класса Conveyor для того чтобы во время тестинга не было никаких затруднений заново руками всё прописывать, и чтобы видеть как этим пользоваться, например.

2018-06-18 08:55 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +    def __init__(self, locks):
Было бы неплохо немного документации втащить, но так как времени мало - заведи для себя бэклог доску в трелло и добавь туда таску на импрув документированности кода. Я лично именно так сделал, буду выполнять эту таску уже после защиты этого курсача

2018-06-24 15:06 UTC, dmitriev-z commented on conveyor/conveyor_hardware_api.py
> +class ConveyorError(Exception):
Ну это типо хардстоп конвейера
Я сам не знаю, в каких случаях это может использоваться
КОГДА ЧТО-ТО ПОЙДЕТ НЕ ТАК
Думал вот, нужно это вообще или нет

2018-06-24 15:23 UTC, dmitriev-z commented on conveyor/conveyor_hardware_api.py
> +        GPIO.output(7, GPIO.HIGH)
Смотрел примеры, там так было реализовано
Думаю, можно просто в инит это положить, так ведь?

2018-06-24 15:34 UTC, dmitriev-z commented on conveyor/conveyor_hardware_api.py
> +        sleep(0.8)
fixed

2018-06-24 15:37 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +class ConveyorError(Exception):
Не думаю, что нужно делать это через Exception. Просто пускай будет атрибут конвейера через енам типо DISABLED, ENABLED, E_STOP, и будет функция которая отправит на конвейер бит естопа и выставит классу статус E_STOP

2018-06-28 00:46 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        GPIO.output(7, GPIO.HIGH)
Ответил выше про то, что нужно ли вообще делать это через Exeption

2018-06-28 00:46 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        GPIO.setmode(GPIO.BCM)
А точно ли это и последующее нужно делать так часто (каждый раз при инициализации класса Lock) может вынести это наверх, после импортов?

2018-06-28 00:48 UTC, dmitriev-z commented on conveyor/conveyor_hardware_api.py
> +        GPIO.setmode(GPIO.BCM)
Ну в принципе да
Можно варнинги и эту строку в самое начало положить

2018-06-28 01:00 UTC, yoshi-lyosha approved these changes
Заводи таски на будущее, фикси помарки и пуш
Всё ок, мне нравится, молодцом!

2018-06-28 01:00 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        for id, lock in enumerate(self._locks):
enumerate может начинаться не только с 0.
`enumerate(self._locks, 1)` в твоём случае

2018-06-28 01:00 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        if lock_id:
судя по тройному повторению этому приёма - напрашивается метод `get_lock_by_id_or_name`

2018-06-28 01:00 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +class Conveyor:
Ты пока решил не добавлять возможность бабахнуть Е-стоп?

2018-06-28 01:00 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +    def name(self):
не уверен что нужно вообще такое количество пропертей. ты ведь только себя самого по рукам бьёшь, а сам ведь знаешь что не нужно это менять. мы же тут не в Си и прочем, у нас тут всё свободно.

2018-06-28 01:00 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        return self._state.name
почему именно `.name` возвращаешь, а не весь объект enum? так разве не было бы проще?

2018-06-28 01:00 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        return {'lock_id': lock.id, 'lock_name': lock.name, 'is_busy': lock.is_busy, 'state': lock.state}
не думаю что такой словарь нужно возвращать прям в классе Конвейера. пусть апишка такое отдаёт. 

А тут ты явно спросил стейт конкретного замка, так и возвращай, например, кортеж (замок, стейт), либо только стейт вообще. Но, наверн кортеж будет проще - можно будет достать и id и name

2018-06-28 01:00 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        return [
Это ок, но однажды ещё подумаем. Бахни себе таску в бэклог типо "подумать поплотнее про хардварный апи, когда будет время"

2018-06-28 01:00 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +class Conveyor:
И добавь, плз, всё-таки таску себе про параллельный релиз нескольких замков. Подумаем и об этом потом.

2018-06-28 01:02 UTC, yoshi-lyosha commented on conveyor/conveyor_test_api.py
> +    class TestLock(TestCase):
Думаю, не обязательно было под with засовывать весь тест заодно. Тебе главное запатчить импорт `from conveyor.conveyor_hardware_api import Lock, Conveyor` где юзается RPi.GPIO

2018-06-28 01:03 UTC, yoshi-lyosha commented on conveyor/conveyor_test_api.py
> +            self.assertEqual(self.cv.locks_state(), expected_locks_state, "Locks states are incorrect")
Тесты, в принципе, ок - но ты не тестишь работу с самим GPIO. Фактически ты полностью доверяешься своей работе с ним, и тестишь логику описанную тобой. Это не полноценно, но пока - сойдёт

2018-06-28 01:12 UTC, dmitriev-z commented on conveyor/conveyor_hardware_api.py
> +        for id, lock in enumerate(self._locks):
принято

2018-06-28 01:13 UTC, dmitriev-z commented on conveyor/conveyor_hardware_api.py
> +        if lock_id:
ага, сделал

2018-06-28 01:14 UTC, dmitriev-z commented on conveyor/conveyor_hardware_api.py
> +        if lock_id:
только вот думаю, нудны ли тогда функции поиска (_find_lock_by_id, _find_lock_by_name)?
или можно прям в тело этого метода перенести их функционал?

2018-06-28 01:15 UTC, dmitriev-z commented on conveyor/conveyor_hardware_api.py
> +class Conveyor:
нет, там же есть метод conveyor_e_stop

2018-06-28 01:15 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        if lock_id:
хм, резонно, возможно и не нужны, но ты пока оставь

2018-06-28 01:16 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +class Conveyor:
а, не углядел, кул!

2018-06-28 01:31 UTC, dmitriev-z commented on conveyor/conveyor_hardware_api.py
> +        return {'lock_id': lock.id, 'lock_name': lock.name, 'is_busy': lock.is_busy, 'state': lock.state}
Ну типо во втором методе, который возвращает стейты всех вообще замков, такой же словарь, то есть переделать и там и там?

2018-06-28 01:33 UTC, yoshi-lyosha commented on conveyor/conveyor_hardware_api.py
> +        return {'lock_id': lock.id, 'lock_name': lock.name, 'is_busy': lock.is_busy, 'state': lock.state}
как сам считаешь нужным и удобным. можешь использовать `collections.namedtuple`

суть в том, что при работе с твоими функциями вне концепции веб-апи будет возникать боль из-за необходимости работы со словарём. это нестандартный тип данных просто

2018-08-18 21:16 UTC, yoshi-lyosha commented
сливай коммиты и вмержим уже

2018-09-22 10:32 UTC, merged